exp_name = "diagstromer"
checkpoint = "-1"
gpu = "0,1,2,3"
debug = false
data = "./data/records/macho/full/fold_0/"
repeat = 1
window_size = 200
no_cache = false
probed = 0.5
rs = 0.2
same = 0.2
norm = "zero-mean"
sampling = true
no_msk_token = false
lr = 1e-5
bs = 2500
patience = 20
num_epochs = 10000
scheduler = false
correct_loss = false
arch = "base"
num_layers = 6
num_heads = 4
head_dim = 64
pe_dim = 256
pe_base = 1000
pe_exp = 2
mixer = 512
dropout = 0.1
m_alpha = -1000000000.0
mask_format = "K"
loss_format = "rmse"
use_leak = true
temperature = 0.0
default_loader = true
